/*
 Navicat Premium Data Transfer

 Source Server         : badhon
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : BADHON

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 25/02/2022 21:44:00
*/


-- ----------------------------
-- Table structure for BLOOD_BANK
-- ----------------------------
DROP TABLE "BADHON"."BLOOD_BANK";
CREATE TABLE "BADHON"."BLOOD_BANK" (
  "BLOOD_BANK_ID" NUMBER(3,0) VISIBLE NOT NULL,
  "BLOOD_BANK_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "BLOOD_GROUP" VARCHAR2(2 BYTE) VISIBLE NOT NULL,
  "AMOUNT" NUMBER(5,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of BLOOD_BANK
-- ----------------------------
INSERT INTO "BADHON"."BLOOD_BANK" VALUES ('1', 'Qud-rat-i-khuda', 'A+', '5');
INSERT INTO "BADHON"."BLOOD_BANK" VALUES ('1', 'Qud-rat-i-khuda', 'b+', '10');

-- ----------------------------
-- Table structure for CONTACT
-- ----------------------------
DROP TABLE "BADHON"."CONTACT";
CREATE TABLE "BADHON"."CONTACT" (
  "DONOR_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "MOBLIE_NO" NUMBER(11,0) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(255 BYTE) VISIBLE,
  "FACEBOOK" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CONTACT
-- ----------------------------

-- ----------------------------
-- Table structure for DISEASES
-- ----------------------------
DROP TABLE "BADHON"."DISEASES";
CREATE TABLE "BADHON"."DISEASES" (
  "DONOR_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "ALARGY" VARCHAR2(1 BYTE) VISIBLE NOT NULL,
  "BLOOD_PRESSURE" VARCHAR2(25 BYTE) VISIBLE,
  "CRONIC_DISEASES" VARCHAR2(1 BYTE) VISIBLE,
  "OTHERS" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DISEASES
-- ----------------------------

-- ----------------------------
-- Table structure for DONOR
-- ----------------------------
DROP TABLE "BADHON"."DONOR";
CREATE TABLE "BADHON"."DONOR" (
  "DONOR_ID" NUMBER(4,0) VISIBLE NOT NULL,
  "DONOR_NAME" VARCHAR2(25 BYTE) VISIBLE NOT NULL,
  "BIRTH_DATE" DATE VISIBLE NOT NULL,
  "BLOOD_GROUP" VARCHAR2(2 BYTE) VISIBLE NOT NULL,
  "LAST_DATE_OF_DONATION" DATE VISIBLE,
  "PHONE_NUMBER" VARCHAR2(255 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(255 BYTE) VISIBLE,
  "LOCATION" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DONOR
-- ----------------------------
INSERT INTO "BADHON"."DONOR" VALUES ('2', 'ismail', TO_DATE('2000-06-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'B+', TO_DATE('2020-09-20 23:14:25', 'SYYYY-MM-DD HH24:MI:SS'), '01780319010', 'ABC@gmail.com', 'Hatirpul');
INSERT INTO "BADHON"."DONOR" VALUES ('1', 'SHAMIM', TO_DATE('2022-06-24 22:03:59', 'SYYYY-MM-DD HH24:MI:SS'), 'A+', TO_DATE('2007-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '01725678768', 'amn@gmail.com', 'Firmgate');
INSERT INTO "BADHON"."DONOR" VALUES ('7', 'Azgor ', TO_DATE('2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'A+', TO_DATE('2020-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '0173485417', 'abc@gmail.com', 'ajimpur');
INSERT INTO "BADHON"."DONOR" VALUES ('3', 'Disa', TO_DATE('2020-08-27 11:07:11', 'SYYYY-MM-DD HH24:MI:SS'), 'O+', TO_DATE('2022-02-03 11:07:44', 'SYYYY-MM-DD HH24:MI:SS'), '01735689312', 'disa@gmail.com', 'Shahbag');

-- ----------------------------
-- Table structure for HOSPITAL
-- ----------------------------
DROP TABLE "BADHON"."HOSPITAL";
CREATE TABLE "BADHON"."HOSPITAL" (
  "HOSPITAL_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "HOSPITAL_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "BLOOD_BANK_ID" NUMBER(3,0) VISIBLE,
  "LOCATION_ID" VARCHAR2(3 BYTE) VISIBLE,
  "PHONE_NUMBHER" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of HOSPITAL
-- ----------------------------

-- ----------------------------
-- Table structure for LOCATION
-- ----------------------------
DROP TABLE "BADHON"."LOCATION";
CREATE TABLE "BADHON"."LOCATION" (
  "LOCATION_ID" VARCHAR2(5 BYTE) VISIBLE NOT NULL,
  "AREA" VARCHAR2(25 BYTE) VISIBLE NOT NULL,
  "DISTRICT" VARCHAR2(25 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of LOCATION
-- ----------------------------

-- ----------------------------
-- Table structure for LOGIN
-- ----------------------------
DROP TABLE "BADHON"."LOGIN";
CREATE TABLE "BADHON"."LOGIN" (
  "USER_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(255 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of LOGIN
-- ----------------------------
INSERT INTO "BADHON"."LOGIN" VALUES ('azgor', '123', 'abc@gmail.com');
INSERT INTO "BADHON"."LOGIN" VALUES ('ruhul', '123', 'abc@gmail.com');
INSERT INTO "BADHON"."LOGIN" VALUES ('ismail', 'choya', 'abc@gmail.com');
INSERT INTO "BADHON"."LOGIN" VALUES ('disa', 'rfregh', 'abc@gmail.com');
INSERT INTO "BADHON"."LOGIN" VALUES ('admin', 'admin', '1805091@ugrad.cse.buet.ac.bd');

-- ----------------------------
-- Table structure for PATIENT
-- ----------------------------
DROP TABLE "BADHON"."PATIENT";
CREATE TABLE "BADHON"."PATIENT" (
  "PATIENT_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "HOSPITAL_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "BLOOD_GROUP" VARCHAR2(2 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENT
-- ----------------------------

-- ----------------------------
-- Table structure for REQUEST
-- ----------------------------
DROP TABLE "BADHON"."REQUEST";
CREATE TABLE "BADHON"."REQUEST" (
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "LOCATION" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "HOSPITAL" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PHONE" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "BLOOD_GROUP" VARCHAR2(255 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of REQUEST
-- ----------------------------
INSERT INTO "BADHON"."REQUEST" VALUES ('Azgor', 'Shahbag', 'Lab aid', '0173485417', 'abc@gmail.com', 'b+');
INSERT INTO "BADHON"."REQUEST" VALUES ('Azgor', 'Shahbag', 'Lab aid', '0173485417', 'abc@gmail.com', 'A+');
INSERT INTO "BADHON"."REQUEST" VALUES ('Disa ', 'firmgate', 'Lab aid', '0173485417', '1805091@ugrad.cse.buet.ac.bd', 'A+');
INSERT INTO "BADHON"."REQUEST" VALUES ('Disa', 'Shahbag', 'square', '0173485417', '1805091@ugrad.cse.buet.ac.bd', 'A+');

-- ----------------------------
-- Table structure for TRANSACTION_ID
-- ----------------------------
DROP TABLE "BADHON"."TRANSACTION_ID";
CREATE TABLE "BADHON"."TRANSACTION_ID" (
  "TRANSACTION_ID" NUMBER(20,0) VISIBLE NOT NULL,
  "PATIENT_ID" NUMBER(5,0) VISIBLE NOT NULL,
  "BLOOD_BANK_ID" NUMBER(3,0) VISIBLE NOT NULL,
  "DATE" DATE VISIBLE NOT NULL,
  "AMOUNT" NUMBER(5,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TRANSACTION_ID
-- ----------------------------

-- ----------------------------
-- Checks structure for table BLOOD_BANK
-- ----------------------------
ALTER TABLE "BADHON"."BLOOD_BANK" ADD CONSTRAINT "SYS_C007512" CHECK ("BLOOD_BANK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."BLOOD_BANK" ADD CONSTRAINT "SYS_C007513" CHECK ("BLOOD_BANK_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."BLOOD_BANK" ADD CONSTRAINT "SYS_C007514" CHECK ("BLOOD_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."BLOOD_BANK" ADD CONSTRAINT "SYS_C007515" CHECK ("AMOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CONTACT
-- ----------------------------
ALTER TABLE "BADHON"."CONTACT" ADD CONSTRAINT "SYS_C007508" PRIMARY KEY ("DONOR_ID");

-- ----------------------------
-- Checks structure for table CONTACT
-- ----------------------------
ALTER TABLE "BADHON"."CONTACT" ADD CONSTRAINT "SYS_C007506" CHECK ("DONOR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."CONTACT" ADD CONSTRAINT "SYS_C007507" CHECK ("MOBLIE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DISEASES
-- ----------------------------
ALTER TABLE "BADHON"."DISEASES" ADD CONSTRAINT "SYS_C007505" PRIMARY KEY ("DONOR_ID");

-- ----------------------------
-- Checks structure for table DISEASES
-- ----------------------------
ALTER TABLE "BADHON"."DISEASES" ADD CONSTRAINT "SYS_C007503" CHECK ("DONOR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."DISEASES" ADD CONSTRAINT "SYS_C007504" CHECK ("ALARGY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DONOR
-- ----------------------------
ALTER TABLE "BADHON"."DONOR" ADD CONSTRAINT "SYS_C007498" PRIMARY KEY ("DONOR_ID");

-- ----------------------------
-- Checks structure for table DONOR
-- ----------------------------
ALTER TABLE "BADHON"."DONOR" ADD CONSTRAINT "SYS_C007495" CHECK ("DONOR_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."DONOR" ADD CONSTRAINT "SYS_C007496" CHECK ("BIRTH_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."DONOR" ADD CONSTRAINT "SYS_C007497" CHECK ("BLOOD_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table HOSPITAL
-- ----------------------------
ALTER TABLE "BADHON"."HOSPITAL" ADD CONSTRAINT "SYS_C007511" PRIMARY KEY ("HOSPITAL_ID");

-- ----------------------------
-- Checks structure for table HOSPITAL
-- ----------------------------
ALTER TABLE "BADHON"."HOSPITAL" ADD CONSTRAINT "SYS_C007509" CHECK ("HOSPITAL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."HOSPITAL" ADD CONSTRAINT "SYS_C007510" CHECK ("HOSPITAL_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LOCATION
-- ----------------------------
ALTER TABLE "BADHON"."LOCATION" ADD CONSTRAINT "SYS_C007502" PRIMARY KEY ("LOCATION_ID");

-- ----------------------------
-- Checks structure for table LOCATION
-- ----------------------------
ALTER TABLE "BADHON"."LOCATION" ADD CONSTRAINT "SYS_C007499" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."LOCATION" ADD CONSTRAINT "SYS_C007500" CHECK ("AREA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."LOCATION" ADD CONSTRAINT "SYS_C007501" CHECK ("DISTRICT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LOGIN
-- ----------------------------
ALTER TABLE "BADHON"."LOGIN" ADD CONSTRAINT "SYS_C007593" PRIMARY KEY ("USER_NAME");

-- ----------------------------
-- Checks structure for table LOGIN
-- ----------------------------
ALTER TABLE "BADHON"."LOGIN" ADD CONSTRAINT "SYS_C007590" CHECK ("USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."LOGIN" ADD CONSTRAINT "SYS_C007591" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."LOGIN" ADD CONSTRAINT "SYS_C007592" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PATIENT
-- ----------------------------
ALTER TABLE "BADHON"."PATIENT" ADD CONSTRAINT "SYS_C007518" PRIMARY KEY ("PATIENT_ID");

-- ----------------------------
-- Checks structure for table PATIENT
-- ----------------------------
ALTER TABLE "BADHON"."PATIENT" ADD CONSTRAINT "SYS_C007516" CHECK ("PATIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."PATIENT" ADD CONSTRAINT "SYS_C007517" CHECK ("HOSPITAL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table REQUEST
-- ----------------------------
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007638" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007639" CHECK ("LOCATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007640" CHECK ("HOSPITAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007641" CHECK ("PHONE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007642" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."REQUEST" ADD CONSTRAINT "SYS_C007643" CHECK ("BLOOD_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TRANSACTION_ID
-- ----------------------------
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007527" PRIMARY KEY ("TRANSACTION_ID");

-- ----------------------------
-- Checks structure for table TRANSACTION_ID
-- ----------------------------
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007522" CHECK ("TRANSACTION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007523" CHECK ("PATIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007524" CHECK ("BLOOD_BANK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007525" CHECK ("DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BADHON"."TRANSACTION_ID" ADD CONSTRAINT "SYS_C007526" CHECK ("AMOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
